# mjolnur/config/exp1_decoded.yaml
cams_zarr: "gs://mjolnur-cams-data/cams/zarr/pm_1deg_conservative.zarr"
use_decoded_cache: false
gc_channels:
  - "10m_u_component_of_wind"
  - "10m_v_component_of_wind"
  - "2m_temperature"
  - "mean_sea_level_pressure"
  - "total_precipitation_6hr"

times:
  start: "2024-01-01T00:00:00"
  stop: "2024-01-07T00:00:00"
  step_hours: 6

train:
  seed: 42
  lr: 5e-4
  steps: 1000
  log_every: 10
  weight_decay: 1e-4
  
model:
  base: 32
  levels: 3